version: '3'
services:
  threads:
    build:
      context: ./services/threads
    environment:
      CONN_STR: postgres://postgres:postgrespassword@host.docker.internal:8432/postgres
      PORT: 4001
    ports: ['4001:4001']
    extra_hosts:
      - "host.docker.internal:host-gateway"
  posts:
    build:
      context: ./services/posts
    environment:
      CONN_STR: postgres://postgres:postgrespassword@host.docker.internal:7432/postgres
      PORT: 4002
    ports: ['4002:4002']
    extra_hosts:
      - "host.docker.internal:host-gateway"
  gateway:
    network_mode: "host"
    build:
      context: ./services/gateway
    depends_on:
      - threads
      - posts
    environment:
      THREAD_URL: http://host.docker.internal:4001/threads
      POST_URL: http://host.docker.internal:4002/posts
      THREAD_URL_BASE: http://host.docker.internal:4001
      THREAD_URL_OAS_SPEC: http://host.docker.internal:4001/openapi-spec
      PORT: 8000
    ports: ['8000:8000']
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "./health-check.sh"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s