version: '3'
services:
  threads:
    build:
      context: ./services/threads
    environment:
      CONN_STR: postgres://postgres:postgrespassword@host.docker.internal:8432/postgres
      PORT: 4001
    ports: ['4001:4001']
    extra_hosts:
      - "host.docker.internal:host-gateway"
  posts:
    build:
      context: ./services/posts
    environment:
      CONN_STR: postgres://postgres:postgrespassword@host.docker.internal:7432/postgres
      PORT: 4002
    ports: ['4002:4002']
    extra_hosts:
      - "host.docker.internal:host-gateway"
  gateway:
    build:
      context: ./services/gateway
    depends_on:
      - threads
      - posts
    environment:
      THREADS_URL: http://host.docker.internal:4001/threads
      POSTS_URL: http://host.docker.internal:4002/posts
      PORT: 8000
    ports: ['8000:8000']
    extra_hosts:
      - "host.docker.internal:host-gateway"